### ISSUE TITLE
Some Forge items fail to update

### ISSUE THREAD

**Issue by rhagelstrom** [bmos/FG-Forge-Updater#116]
Exhausted fails to update the forge with the following error. I haven't looked into it any more than that.
I also see extra planer containers also is experiencing the same issue

2024-10-26 21:21:06,152 : INFO : File upload path determined to be: /home/runner/work/Exhausted/Exhausted/Exhausted.ext
2024-10-26 21:21:16,432 : INFO : Logged in as rhagelstrom
2024-10-26 21:21:24,559 : INFO : Already logged in
2024-10-26 21:21:24,559 : INFO : Uploading new build to Forge item
Traceback (most recent call last):
  File "/home/runner/work/Exhausted/Exhausted/src/main.py", line 64, in <module>
    main()
  File "/home/runner/work/Exhausted/Exhausted/src/main.py", line 57, in main
    item.upload_and_publish(s, urls, new_files, channel)
  File "/home/runner/work/Exhausted/Exhausted/src/forge_api.py", line 135, in upload_and_publish
    self.add_build(session.driver, new_files)
  File "/home/runner/work/Exhausted/Exhausted/src/forge_api.py", line 147, in add_build
    add_file_to_dropzone(driver, self.timeout, build)
  File "/home/runner/work/Exhausted/Exhausted/src/dropzone.py", line 70, in add_file_to_dropzone
    uploads_tab.click()
  File "/home/runner/work/Exhausted/Exhausted/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/runner/work/Exhausted/Exhausted/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/Exhausted/Exhausted/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/runner/work/Exhausted/Exhausted/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a class="nav-link" id="manage-build-uploads-tab" data-toggle="tab" href="#manage-build-uploads" role="tab" aria-controls="manage-build-uploads" aria-selected="false">...</a> is not clickable at point (257, 68). Other element would receive the click: <div class="collapse navbar-collapse" id="forge-navbar-collapse">...</div>
  (Session info: chrome=130.0.6723.58)
Stacktrace:
#0 0x560080c220aa <unknown>
#1 0x5600807391a0 <unknown>
#2 0x56008078c896 <unknown>
#3 0x56008078a82d <unknown>
#4 0x5600807882d7 <unknown>
#5 0x5600807876f1 <unknown>
#6 0x56008077acf8 <unknown>
#7 0x5600807a9d82 <unknown>
#8 0x56008077a6d8 <unknown>
#9 0x5600807a9f4e <unknown>
#10 0x5600807c8866 <unknown>
#11 0x5600807a9b23 <unknown>
#12 0x560080778990 <unknown>
#13 0x56008077996e <unknown>
#14 0x560080bee16b <unknown>
#15 0x560080bf1f68 <unknown>
#16 0x560080bdb64c <unknown>
#17 0x560080bf2ae7 <unknown>
#18 0x560080bc04af <unknown>
#19 0x560080c104f8 <unknown>
#20 0x560080c106c0 <unknown>
#21 0x560080c20f26 <unknown>
#22 0x7f8853894ac3 <unknown>

**Comment by bmos** [comment]
I have had this happen also.
