### ISSUE TITLE
Documentation Table Output on new Forge Layout

### ISSUE THREAD

**Issue by rhagelstrom** [bmos/FG-Forge-Updater#81]
Hard to read

https://forge.fantasygrounds.com/shop/items/32/view

**Comment by bmos** [comment]
Oooh Forge re-skin?
I wonder if I can style it with css or something rather than using specific colors.

**Comment by rhagelstrom** [comment]
They must have also changed/moved some other stuff around because I'm getting an upload error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/BetterCombatEffects/BetterCombatEffects/src/main.py", line 64, in <module>
    main()
  File "/home/runner/work/BetterCombatEffects/BetterCombatEffects/src/main.py", line 57, in main
    item.upload_and_publish(s, urls, new_files, channel)
  File "/home/runner/work/BetterCombatEffects/BetterCombatEffects/src/forge_api.py", line 130, in upload_and_publish
    self.login(session, urls)
  File "/home/runner/work/BetterCombatEffects/BetterCombatEffects/src/forge_api.py", line 108, in login
    raise TimeoutException("No username or password field found, or login button is not clickable.") from e
selenium.common.exceptions.TimeoutException: Message: No username or password field found, or login button is not clickable.

**Comment by bmos** [comment]
![image](https://github.com/user-attachments/assets/961447c1-2d81-4b92-adc3-cb8bb42e073a)
